/**
 * NAPI-RS generated bindings
 *
 * This file will be generated by @napi-rs/cli during build.
 * The actual binding is placed in a platform-specific .node file.
 *
 * For manual loading (fallback), try:
 * const os = require('os');
 * const path = require('path');
 * const platform = os.platform();
 * const arch = os.arch();
 * // ... construct platform-specific name
 * module.exports = require(path.join(__dirname, `dotenvage-napi.${platformName}.node`));
 *
 * However, @napi-rs/cli generates this automatically, so this is just a placeholder.
 */

// This will be generated by @napi-rs/cli build command
// For now, export a helpful error message
module.exports = new Proxy(
  {},
  {
    get(target, prop) {
      throw new Error(
        `dotenvage-napi native bindings not found. Please run 'npm run build' to compile the native addon.`
      );
    },
  }
);
